sudo: require
dist: xenial
language: bash

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y
    texlive-base
    texlive-latex-base
    texlive-latex-extra
    texlive-fonts-recommended
    texlive-fonts-extra
    texlive-science
    biber
    chktex

install: true

script:
  - ./test.sh

notifications:
  email:
    on_success: change
    on_failure: change
